package wanbao.yongchao.com.wanbao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wanbao.yongchao.com.wanbao.db.db.BusinessDB;
import wanbao.yongchao.com.wanbao.db.db.UserDB;

import wanbao.yongchao.com.wanbao.db.BusinessDBDao;
import wanbao.yongchao.com.wanbao.db.UserDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig businessDBDaoConfig;
    private final DaoConfig userDBDaoConfig;

    private final BusinessDBDao businessDBDao;
    private final UserDBDao userDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        businessDBDaoConfig = daoConfigMap.get(BusinessDBDao.class).clone();
        businessDBDaoConfig.initIdentityScope(type);

        userDBDaoConfig = daoConfigMap.get(UserDBDao.class).clone();
        userDBDaoConfig.initIdentityScope(type);

        businessDBDao = new BusinessDBDao(businessDBDaoConfig, this);
        userDBDao = new UserDBDao(userDBDaoConfig, this);

        registerDao(BusinessDB.class, businessDBDao);
        registerDao(UserDB.class, userDBDao);
    }
    
    public void clear() {
        businessDBDaoConfig.clearIdentityScope();
        userDBDaoConfig.clearIdentityScope();
    }

    public BusinessDBDao getBusinessDBDao() {
        return businessDBDao;
    }

    public UserDBDao getUserDBDao() {
        return userDBDao;
    }

}
